# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EATR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EATR
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'AlamofireImage', '~> 4.1'
pod 'Moya', '~> 14.0'

end
